services:
  #Local container swapped for amazon 

  analytics:
    build:
      context: ../analytics-service
      dockerfile: Dockerfile
    container_name: financial-analytics
    ports:
      - "8082:8080" ### Changed to 8082 for multi level evaluation
    networks:
      - financial-network
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: financial-backend
    ports:
      - "8081:8081"
    environment:
      
      - SPRING_PROFILES_ACTIVE=prod 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - analytics
    networks:
      - financial-network
    restart: always
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: financial-frontend
    ports:
      - "80:80"  
    depends_on:
      - backend
    networks:
      - financial-network
    restart: always 
networks:
  financial-network:
    driver: bridge


