server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/financial_db # Target port shifted to 5433
    username: financial_user
    password: password123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
